name: Apple Silicon Build
on: workflow_dispatch
jobs:
 build-macos:
    runs-on: macos-11.0
    name: Build on darwin-arm64
    steps:
      - name: Update binaries
        run: |
          brew install autoconf automake libtool cmake
          wget https://www.openssl.org/source/openssl-1.1.1.tar.gz
          tar -xvzf openssl-1.1.1.tar.gz
          cd openssl-1.1.1/
          ./Configure darwin64-arm64-cc --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
          make -j$(($(nproc)+1))
          sudo make install
          sudo echo 'LD_LIBRARY_PATH=/usr/local/ssl/lib:${LD_LIBRARY_PATH}' >> /etc/environment
          rm openssl-1.1.1.tar.gz
          sudo rm openssl-1.1.1 -r
          git clone --recursive https://github.com/cirospaciari/http-proxy.git
          cd ./http-proxy
          make macos-arm64
          mkdir -p bin/macos
          mv http_proxy bin/macos-arm64/http_proxy
          git add bin/macos-arm64/http_proxy
          git config --global user.email "ciro.spaciari@gmail.com"
          git config --global user.name "Ciro Spaciari"
          git commit -m "[GitHub Actions] Updated darwin-arm64 binaries" || true
          git push "https://cirospaciari:${{ secrets.BUILDTOKEN }}@github.com/cirospaciari/http-proxy.git"
